export const PRISMIC_API_CONNECTION_REQUEST = 'containers/App/PRISMIC_API_CONNECTION_REQUEST';
export const PRISMIC_API_CONNECTION_CONNECTED = 'containers/App/PRISMIC_API_CONNECTION_CONNECTED';
export const PRISMIC_API_CONNECTION_ERROR = 'containers/App/PRISMIC_API_CONNECTION_ERROR';
